# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f56676f21d427973ec2a52626010eece33c71e1d2b93b303e193557e07db6ef86165ed4fdbc65aed0403b60e6316f605d3853fc18b6a240cd61dfa1e253acb45

test:
  secret_key_base: 8a237d01aeb61841fdb5a14f03e46435f2a0c14a459d14ad76817913a10bc63803bdee066a2963d8baee2cd22360c09940337a82c760af3d62ad4425761634f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
